// Generated by CoffeeScript 1.4.0
(function() {
  var cheerio, execCall, fs, http, theme, themes, titleRe;

  cheerio = require('cheerio');

  http = require('http');

  fs = require('fs');

  themes = {
    'politics': 5,
    'culture': 2,
    'health': 3,
    'society': 3,
    'economy': 3,
    'sport': 1,
    'education': 3,
    'free-speech-debate': 2,
    'religion': 2,
    'philosophy': 2,
    'science': 2,
    'environment': 2,
    'law': 4,
    'international': 5
  };

  titleRe = new RegExp("<title>(.*?)</title>");

  execCall = function(theme) {
    var page, url, _i, _ref, _results;
    if (!fs.existsSync(theme)) {
      fs.mkdirSync(theme);
    }
    _results = [];
    for (page = _i = 0, _ref = themes[theme]; 0 <= _ref ? _i < _ref : _i > _ref; page = 0 <= _ref ? ++_i : --_i) {
      url = "http://idebate.org/debatabase/themes/" + theme + "?page=" + page;
      console.log("URL: " + url);
      _results.push(http.get(url, function(listRes) {
        var listBody;
        if (listRes.statusCode === 200) {
          listBody = '';
          listRes.on('data', function(chunk) {
            return listBody += chunk;
          });
          return listRes.on('end', function() {
            var $;
            console.log("Loaded list");
            $ = cheerio.load(listBody);
            return $('.views-field-title a').each(function(index) {
              var pageBody, pageHref, pageReq;
              pageHref = 'http://idebate.org' + $(this).attr('href');
              pageBody = '';
              return pageReq = http.get(pageHref, function(pageRes) {
                return pageRes.on('data', function(pageChunk) {
                  var canIndex, endIndex, id, printHref, printReq, startIndex;
                  pageChunk = pageChunk.toString();
                  canIndex = pageChunk.indexOf('rel="canonical"');
                  if (canIndex > -1) {
                    startIndex = canIndex + 46;
                    endIndex = pageChunk.indexOf('" />', startIndex);
                    id = pageChunk.substring(startIndex, endIndex);
                    printHref = "http://idebate.org/print/" + id;
                    console.log("Got href from page " + printHref);
                    return printReq = http.get(printHref, function(printRes) {
                      var printBody;
                      printBody = '';
                      printRes.on('data', function(printChunk) {
                        return printBody += printChunk;
                      });
                      return printRes.on('end', function() {
                        var printString, title;
                        printString = printBody.toString();
                        title = printString.match(titleRe);
                        title = title[1];
                        console.log("Got print " + title);
                        console.log(theme);
                        return fs.writeFile("./digest/" + theme + "/" + title + ".html", printString, function(err) {
                          if (err) {
                            return console.log(err.message);
                          }
                        });
                      });
                    });
                  }
                });
              });
            });
          });
        }
      }));
    }
    return _results;
  };

  for (theme in themes) {
    execCall(theme);
  }

}).call(this);
